version: '3'

services:
  db:
    image: postgres:13

    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_DB=jeugdzorg
      - POSTGRES_PASSWORD=postgres

  dbadmin:
    image: fenglc/pgadmin4:2-python3.6-alpine
    environment:
      - DEFAULT_USER=admin
      - DEFAULT_PASSWORD=admin
    ports:
      - "5050:5050"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile-development
    restart: always
    volumes:
      - ./jeugdzorg:/opt/app
      - ./media:/opt/file_upload
    environment:
      - ENV=develop
      - DJANGO_ENV=dev
      - RUNSERVER=yes
      - POSTGRES_DB=jeugdzorg
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ADMIN_USERNAME=user_vraagmij
      - ADMIN_PASSWORD=password_vraagmij
      - ADMIN_EMAIL=user@example.com
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  pg_data: {}
  pg_backups: {}