# Generated by Django 2.0.1 on 2018-01-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_field', models.CharField(max_length=100, verbose_name='Some')),
            ],
        ),
    ]
