# Generated by Django 2.0.1 on 2018-02-08 10:52

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0002_mymodel_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='titel')),
            ],
        ),
        migrations.CreateModel(
            name='Voorwaarde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='titel')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='regeling',
            name='voorwaarde_lijst',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='jeugdzorg.Voorwaarde'),
        ),
    ]
