# Generated by Django 2.0.8 on 2020-05-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0002_auto_20180424_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regelingtag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='regelingtag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggedregeling',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeugdzorg_taggedregeling_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggedregeling',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
    ]
