# Generated by Django 2.0.2 on 2018-03-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0002_profiel_vaardigheden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gebied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Gebied',
                'verbose_name_plural': 'Gebieden',
                'ordering': ('naam',),
            },
        ),
        migrations.CreateModel(
            name='Stadsdeel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100, verbose_name='Naam')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Stadsdeel',
                'verbose_name_plural': 'Stadsdelen',
                'ordering': ('naam',),
            },
        ),
        migrations.AddField(
            model_name='gebied',
            name='stadsdeel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jeugdzorg.Stadsdeel', verbose_name='Stadsdeel'),
        ),
    ]
