# Generated by Django 2.0.1 on 2018-02-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0003_auto_20180208_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regeling',
            options={'verbose_name': 'Regeling', 'verbose_name_plural': 'Regelingen'},
        ),
        migrations.AlterModelOptions(
            name='voorwaarde',
            options={'verbose_name': 'Voorwaarde', 'verbose_name_plural': 'Voorwaarden'},
        ),
        migrations.AddField(
            model_name='regeling',
            name='bron',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bron'),
        ),
        migrations.AddField(
            model_name='regeling',
            name='einddatum',
            field=models.DateField(blank=True, null=True, verbose_name='Eind datum'),
        ),
        migrations.AddField(
            model_name='regeling',
            name='samenvatting',
            field=models.TextField(blank=True, null=True, verbose_name='Samenvatting'),
        ),
        migrations.AddField(
            model_name='regeling',
            name='startdatum',
            field=models.DateField(blank=True, null=True, verbose_name='Start datum'),
        ),
    ]
