# Generated by Django 2.0.1 on 2018-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0004_auto_20180208_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voorwaarde',
            options={'ordering': ['order'], 'verbose_name': 'Voorwaarde', 'verbose_name_plural': 'Voorwaarden'},
        ),
        migrations.RemoveField(
            model_name='regeling',
            name='voorwaarde_lijst',
        ),
        migrations.AddField(
            model_name='voorwaarde',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
