# Generated by Django 2.0.2 on 2018-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0004_profiel_gebied_lijst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='gebied_lijst',
            field=models.ManyToManyField(blank=True, to='jeugdzorg.Gebied', verbose_name='Gebieden'),
        ),
    ]
