# Generated by Django 2.0.2 on 2018-03-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0005_auto_20180314_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telefoonnummer_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Secundair telefoonnummer'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_saved',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date saved'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telefoonnummer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Primair telefoonnummer '),
        ),
    ]
