# Generated by Django 2.0.1 on 2018-02-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0005_auto_20180208_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeling',
            name='voorwaarde_lijst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Voorwaarde', verbose_name='Voorwaarden'),
        ),
    ]
