# Generated by Django 2.0.2 on 2018-03-14 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0006_auto_20180314_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
    ]
