# Generated by Django 2.0.2 on 2018-03-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0007_eventitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='seconden_niet_gebruikt',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seconden niet gebruikt'),
        ),
    ]
