# Generated by Django 2.0.2 on 2018-03-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0008_profiel_seconden_niet_gebruikt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Session id'),
        ),
    ]
