# Generated by Django 2.0.1 on 2018-02-08 14:02

import adminsortable.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0008_remove_regeling_voorwaarde_lijst'),
    ]

    operations = [
        migrations.AddField(
            model_name='voorwaarde',
            name='regeling',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Regeling', verbose_name='Regeling'),
        ),
    ]
