# Generated by Django 2.0.2 on 2018-03-21 15:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0009_auto_20180316_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='telefoonnummer_2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Secundair telefoonnummer'),
        ),
    ]
