# Generated by Django 2.0.1 on 2018-02-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0009_voorwaarde_regeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegelingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('omschrijving', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='regeling',
            options={'ordering': ('-id',), 'verbose_name': 'Regeling', 'verbose_name_plural': 'Regelingen'},
        ),
    ]
