# Generated by Django 2.0.2 on 2018-03-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('jeugdzorg', '0010_profiel_telefoonnummer_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_mail_frequentie', models.CharField(default='0 0 1 * *', help_text='Standaard is maandelijks.', max_length=30, verbose_name='Update mail frequentie')),
                ('update_mail_content', models.TextField(blank=True, null=True, verbose_name='Update mail content')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Site')),
            ],
        ),
    ]
