# Generated by Django 2.0.1 on 2018-02-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jeugdzorg', '0010_auto_20180215_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedRegeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeugdzorg_taggedregeling_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jeugdzorg_taggedregeling_items', to='jeugdzorg.RegelingTag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
