# Generated by Django 2.0.2 on 2018-03-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0011_instelling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instelling',
            options={'verbose_name': 'Instelling', 'verbose_name_plural': 'Instellingen'},
        ),
        migrations.AlterField(
            model_name='instelling',
            name='update_mail_frequentie',
            field=models.CharField(default='0 0 1 * *', help_text="Standaard is maandelijks. Crontab format 'MIN HOUR DOM MON DOW CMD'", max_length=30, verbose_name='Update mail frequentie'),
        ),
    ]
