# Generated by Django 2.0.1 on 2018-02-15 10:33

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0012_regeling_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regeling',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='jeugdzorg.TaggedRegeling', to='jeugdzorg.RegelingTag', verbose_name='Tags'),
        ),
    ]
