# Generated by Django 2.0.2 on 2018-03-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0012_auto_20180321_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='hou_me_op_de_hoogte_mail',
            field=models.BooleanField(default=False, verbose_name='Hou me op de hoogte via e-mail'),
        ),
    ]
