# Generated by Django 2.0.1 on 2018-02-15 12:43

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0013_auto_20180215_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255, verbose_name='Titel')),
                ('omschrijving', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
            ],
        ),
        migrations.AddField(
            model_name='regeling',
            name='doelen',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='jeugdzorg.Doel'),
        ),
    ]
