# Generated by Django 2.0.2 on 2018-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0013_profiel_hou_me_op_de_hoogte_mail'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ONLY public.django_admin_log DROP CONSTRAINT django_admin_log_user_id_c564eba6_fk",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "ALTER TABLE ONLY django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk FOREIGN KEY (user_id) REFERENCES jeugdzorg_user(id) DEFERRABLE INITIALLY DEFERRED",
            migrations.RunSQL.noop
        ),
    ]
