# Generated by Django 2.0.2 on 2018-03-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0014_auto_20180322_1358'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ONLY public.auth_user_groups DROP CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id;",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "ALTER TABLE ONLY auth_user_groups ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES jeugdzorg_user(id) DEFERRABLE INITIALLY DEFERRED;",
            migrations.RunSQL.noop
        ),
    ]
