# Generated by Django 2.0.2 on 2018-03-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0015_auto_20180323_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='instelling',
            name='app_naam',
            field=models.CharField(blank=True, default='VraagMij', max_length=30, null=True, verbose_name='App naam'),
        ),
        migrations.AddField(
            model_name='instelling',
            name='standaard_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Standaard contact e-mailadres'),
        ),
        migrations.AddField(
            model_name='instelling',
            name='standaard_contact_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Standaard contact naam'),
        ),
    ]
