# Generated by Django 2.0.2 on 2018-03-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0016_auto_20180323_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='gebruiker_email_verificatie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gebruiker email verificatie'),
        ),
    ]
