# Generated by Django 2.0.1 on 2018-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0016_auto_20180215_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeling',
            name='datum_gecreeerd',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum gecreëerd'),
        ),
        migrations.AddField(
            model_name='regeling',
            name='datum_opgeslagen',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum opgeslagen'),
        ),
        migrations.AddField(
            model_name='voorwaarde',
            name='datum_gecreeerd',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum gecreëerd'),
        ),
        migrations.AddField(
            model_name='voorwaarde',
            name='datum_opgeslagen',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum opgeslagen'),
        ),
    ]
