# Generated by Django 2.0.2 on 2018-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0017_profiel_gebruiker_email_verificatie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='gebruiker_email_verificatie',
            field=models.CharField(blank=True, default='valid', max_length=100, null=True, verbose_name='Gebruiker email verificatie'),
        ),
    ]
