# Generated by Django 2.0.1 on 2018-02-16 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0018_auto_20180215_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=100, verbose_name='Voornaam')),
                ('achternaam', models.CharField(max_length=100, verbose_name='Achternaam')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mailadres')),
                ('telefoonnummer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefoonnummer')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacten',
            },
        ),
        migrations.CreateModel(
            name='ContactNaarRegeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Contact', verbose_name='Contact')),
                ('regeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Regeling', verbose_name='Regeling')),
            ],
            options={
                'verbose_name': 'Contact naar regeling',
                'verbose_name_plural': 'Contacten naar regelingen',
                'ordering': ('volgorde',),
            },
        ),
        migrations.AddField(
            model_name='regeling',
            name='contact',
            field=models.ManyToManyField(through='jeugdzorg.ContactNaarRegeling', to='jeugdzorg.Contact'),
        ),
    ]
