# Generated by Django 2.0.2 on 2018-03-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0018_auto_20180326_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='instelling',
            name='gebruiker_email_verificatie_frequentie',
            field=models.CharField(default='0 0 1 * *', help_text="Standaard is maandelijks. Crontab format 'MIN HOUR DOM MON DOW'", max_length=30, verbose_name='Gebruiker email verificatie frequentie'),
        ),
        migrations.AlterField(
            model_name='instelling',
            name='update_mail_frequentie',
            field=models.CharField(default='0 0 1 * *', help_text="Standaard is maandelijks. Crontab format 'MIN HOUR DOM MON DOW'", max_length=30, verbose_name='Update mail frequentie'),
        ),
    ]
