# Generated by Django 2.0.1 on 2018-02-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0019_auto_20180216_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactnaarregeling',
            unique_together={('contact', 'regeling')},
        ),
    ]
