# Generated by Django 2.0.2 on 2018-03-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0019_auto_20180326_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='gebruiker_email_verificatie_details',
            field=models.CharField(blank=True, default='valid', max_length=100, null=True, verbose_name='Gebruiker email verificatie details'),
        ),
    ]
