# Generated by Django 2.0.1 on 2018-02-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0020_auto_20180216_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnaarregeling',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactnaarregeling', to='jeugdzorg.Contact', verbose_name='Contact'),
        ),
    ]
