# Generated by Django 2.0.2 on 2018-03-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0021_auto_20180327_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instelling',
            old_name='update_mail_frequentie',
            new_name='send_update_mail_frequentie',
        ),
    ]
