# Generated by Django 2.0.1 on 2018-02-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0021_auto_20180216_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeling',
            name='bron_html_query',
            field=models.TextField(blank=True, null=True, verbose_name='Bron html queryselector'),
        ),
    ]
