# Generated by Django 2.0.2 on 2018-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0022_auto_20180327_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='instelling',
            name='update_mail_content_html',
            field=models.TextField(blank=True, null=True, verbose_name='Update mail content html'),
        ),
    ]
