# Generated by Django 2.0.2 on 2018-03-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0023_instelling_update_mail_content_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='organisatie',
        ),
        migrations.AlterUniqueTogether(
            name='contactnaarorganisatie',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactnaarorganisatie',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactnaarorganisatie',
            name='organisatie',
        ),
        migrations.AlterUniqueTogether(
            name='contactnaarregeling',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactnaarregeling',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactnaarregeling',
            name='regeling',
        ),
        migrations.AlterUniqueTogether(
            name='contactnaarthema',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactnaarthema',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactnaarthema',
            name='thema',
        ),
        migrations.RemoveField(
            model_name='regeling',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='thema',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactNaarOrganisatie',
        ),
        migrations.DeleteModel(
            name='ContactNaarRegeling',
        ),
        migrations.DeleteModel(
            name='ContactNaarThema',
        ),
    ]
