# Generated by Django 2.0.1 on 2018-02-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0023_regeling_bron_veranderd'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeling',
            name='bron_resultaat',
            field=models.TextField(blank=True, null=True, verbose_name='Bron resultaat'),
        ),
    ]
