# Generated by Django 2.0.2 on 2018-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0024_auto_20180328_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisatie',
            name='email_domeinen',
            field=models.TextField(blank=True, help_text='Voer meerdere domeinnamen in door ze met een komma te scheiden.', null=True, verbose_name='E-mailadres domeinen'),
        ),
    ]
