# Generated by Django 2.0.1 on 2018-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0024_regeling_bron_resultaat'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeling',
            name='aanvraag_url',
            field=models.URLField(blank=True, null=True, verbose_name='Aaanvraag url'),
        ),
    ]
