# Generated by Django 2.0.1 on 2018-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0025_regeling_aanvraag_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnaarregeling',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Pas foto'),
        ),
    ]
