# Generated by Django 2.0.2 on 2018-04-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0026_auto_20180329_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronjobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_command', models.CharField(max_length=255, verbose_name='Naam')),
                ('datumtijd_command', models.DateTimeField(verbose_name='Datumtijd')),
                ('log_command', models.TextField(blank=True, null=True, verbose_name='Log')),
            ],
            options={
                'verbose_name': 'Cronjob status',
                'verbose_name_plural': 'Cronjob statussen',
            },
        ),
    ]
