# Generated by Django 2.0.1 on 2018-02-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0026_contactnaarregeling_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactnaarregeling',
            name='photo',
        ),
    ]
