# Generated by Django 2.0.2 on 2018-04-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0027_cronjobstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobstate',
            name='datumtijd_string',
            field=models.CharField(default='', max_length=255, verbose_name='Datumtijd tekst'),
            preserve_default=False,
        ),
    ]
