# Generated by Django 2.0.1 on 2018-02-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0027_remove_contactnaarregeling_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Pas foto'),
        ),
    ]
