# Generated by Django 2.0.2 on 2018-04-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0028_cronjobstate_datumtijd_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjobstate',
            name='datumtijd_command',
        ),
    ]
