# Generated by Django 2.0.1 on 2018-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0029_auto_20180228_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Pas foto'),
        ),
    ]
