# Generated by Django 2.0.2 on 2018-04-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0029_remove_cronjobstate_datumtijd_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='instelling',
            name='mail_account_active_check_frequentie',
            field=models.CharField(default='0 0 1 */6 *', help_text="Standaard is maandelijks. Crontab format 'MIN HOUR DOM MON DOW'", max_length=30, verbose_name='E-mailaccount actief check frequentie'),
        ),
    ]
