# Generated by Django 2.0.1 on 2018-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0030_auto_20180228_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naam')),
                ('waarde', models.CharField(blank=True, max_length=255, null=True, verbose_name='Waarde')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('timestamp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Timestamp')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Event id')),
            ],
        ),
    ]
