# Generated by Django 2.0.2 on 2018-04-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0030_instelling_mail_account_active_check_frequentie'),
    ]

    operations = [
        migrations.AddField(
            model_name='instelling',
            name='create_crontabs_frequentie',
            field=models.CharField(default='*/5 * * * *', help_text="Crontab format 'MIN HOUR DOM MON DOW'", max_length=30, verbose_name='Vernieuw crontabs frequentie'),
        ),
    ]
