# Generated by Django 2.0.1 on 2018-03-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0031_statitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatItem',
        ),
    ]
