# Generated by Django 2.0.2 on 2018-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0032_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='hou_me_op_de_hoogte_mail',
            field=models.BooleanField(default=True, verbose_name='Hou me op de hoogte via e-mail'),
        ),
    ]
