# Generated by Django 2.0.1 on 2018-03-01 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0033_eventitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='eventitem',
            name='waarde',
        ),
    ]
