# Generated by Django 2.0.1 on 2018-03-01 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jeugdzorg', '0034_auto_20180301_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event id'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker'),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Waarde'),
        ),
    ]
