# Generated by Django 2.0.1 on 2018-03-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0035_auto_20180301_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='naam',
        ),
    ]
