# Generated by Django 2.0.1 on 2018-03-01 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0037_eventitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNaarDoel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Contact naar thema',
                'verbose_name_plural': "Contacten naar thema's",
                'ordering': ('volgorde',),
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Pasfoto'),
        ),
        migrations.AddField(
            model_name='contactnaardoel',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactnaardoel', to='jeugdzorg.Contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='contactnaardoel',
            name='doel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Doel', verbose_name='Thema'),
        ),
        migrations.AddField(
            model_name='doel',
            name='contact',
            field=models.ManyToManyField(through='jeugdzorg.ContactNaarDoel', to='jeugdzorg.Contact'),
        ),
        migrations.AlterUniqueTogether(
            name='contactnaardoel',
            unique_together={('contact', 'doel')},
        ),
    ]
