# Generated by Django 2.0.1 on 2018-03-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0039_auto_20180301_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNaarOrganisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactnaarorganisatie', to='jeugdzorg.Contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Contact naar organisatie',
                'verbose_name_plural': 'Contacten naar organisaties',
                'ordering': ('volgorde',),
            },
        ),
        migrations.CreateModel(
            name='Organisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255, verbose_name='Naam')),
            ],
            options={
                'verbose_name': 'Organisatie',
                'verbose_name_plural': 'Organisaties',
            },
        ),
        migrations.AddField(
            model_name='contactnaarorganisatie',
            name='organisatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jeugdzorg.Organisatie', verbose_name='Organistie'),
        ),
        migrations.AddField(
            model_name='contact',
            name='organisatie',
            field=models.ManyToManyField(through='jeugdzorg.ContactNaarOrganisatie', to='jeugdzorg.Organisatie'),
        ),
        migrations.AlterUniqueTogether(
            name='contactnaarorganisatie',
            unique_together={('contact', 'organisatie')},
        ),
    ]
