# Generated by Django 2.0.1 on 2018-03-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0040_auto_20180302_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventitem',
            name='user',
        ),
    ]
