# Generated by Django 2.0.1 on 2018-03-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0041_remove_eventitem_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doel',
            new_name='Thema',
        ),
    ]
