# Generated by Django 2.0.1 on 2018-03-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0042_auto_20180302_1028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactNaarDoel',
            new_name='ContactNaarThema',
        ),
    ]
