# Generated by Django 2.0.1 on 2018-03-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0043_auto_20180302_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regeling',
            old_name='doelen',
            new_name='themas',
        ),
    ]
