# Generated by Django 2.0.1 on 2018-03-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0045_auto_20180302_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnaarthema',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactnaarthema', to='jeugdzorg.Contact', verbose_name='Contact'),
        ),
    ]
