# Generated by Django 2.0.2 on 2018-03-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0048_user'),
    ]

    operations = [
        migrations.RunSQL(
            "INSERT INTO jeugdzorg_user SELECT * FROM auth_user",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "INSERT INTO jeugdzorg_user_groups SELECT * FROM auth_user_groups",
            migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "INSERT INTO jeugdzorg_user_user_permissions SELECT * FROM auth_user_user_permissions",
            migrations.RunSQL.noop
        ),
    ]
