# Generated by Django 2.0.2 on 2018-03-06 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0049_auto_20180305_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Primair e-mailadres')),
                ('telefoonnummer', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='Primair telefoonnummer')),
                ('gebruik_email', models.BooleanField(default=True, verbose_name='Gebruik e-mailadres')),
                ('gebruik_telefoonnummer', models.BooleanField(default=True, verbose_name='Gebruik telefoonnummer')),
            ],
            options={
                'verbose_name': 'Profiel',
                'verbose_name_plural': 'Profielen',
            },
        ),
        migrations.AlterModelOptions(
            name='eventitem',
            options={'verbose_name': 'Gebruikers gedrag', 'verbose_name_plural': 'Gebruikers gedragingen'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Gebruiker', 'verbose_name_plural': 'Gebruikers'},
        ),
        migrations.AddField(
            model_name='profiel',
            name='gebruiker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
