# Generated by Django 2.0.2 on 2018-03-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0051_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfielNaarOrganisatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
                ('organisatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisatienaarprofiel', to='jeugdzorg.Organisatie', verbose_name='Organistie')),
            ],
            options={
                'verbose_name': 'Profiel naar organisatie',
                'verbose_name_plural': 'Profielen naar organisaties',
                'ordering': ('volgorde',),
            },
        ),
        migrations.CreateModel(
            name='ProfielNaarRegeling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Profiel naar regeling',
                'verbose_name_plural': 'Profielen naar regelingen',
                'ordering': ('volgorde',),
            },
        ),
        migrations.CreateModel(
            name='ProfielNaarThema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgorde', models.IntegerField(default=0, verbose_name='Volgorde')),
                ('rol', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Profiel naar thema',
                'verbose_name_plural': "Profielen naar thema's",
                'ordering': ('volgorde',),
            },
        ),
        migrations.AddField(
            model_name='profiel',
            name='achternaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Achternaam'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='functie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Functie'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact', verbose_name='Pasfoto'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='tussenvoegels',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tussenvoegels'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='voornaam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Voornaam'),
        ),
        migrations.AddField(
            model_name='profielnaarthema',
            name='profiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profielnaarthema', to='jeugdzorg.Profiel', verbose_name='Profiel'),
        ),
        migrations.AddField(
            model_name='profielnaarthema',
            name='thema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themanaarprofiel', to='jeugdzorg.Thema', verbose_name='Thema'),
        ),
        migrations.AddField(
            model_name='profielnaarregeling',
            name='profiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profielnaarregeling', to='jeugdzorg.Profiel', verbose_name='Profiel'),
        ),
        migrations.AddField(
            model_name='profielnaarregeling',
            name='regeling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regelingnaarprofiel', to='jeugdzorg.Regeling', verbose_name='Regeling'),
        ),
        migrations.AddField(
            model_name='profielnaarorganisatie',
            name='profiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profielnaarorganisatie', to='jeugdzorg.Profiel', verbose_name='Profiel'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='organisatie_lijst',
            field=models.ManyToManyField(through='jeugdzorg.ProfielNaarOrganisatie', to='jeugdzorg.Organisatie'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='regeling_lijst',
            field=models.ManyToManyField(through='jeugdzorg.ProfielNaarRegeling', to='jeugdzorg.Regeling'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='thema_lijst',
            field=models.ManyToManyField(through='jeugdzorg.ProfielNaarThema', to='jeugdzorg.Thema'),
        ),
        migrations.AlterUniqueTogether(
            name='profielnaarthema',
            unique_together={('profiel', 'thema')},
        ),
        migrations.AlterUniqueTogether(
            name='profielnaarregeling',
            unique_together={('profiel', 'regeling')},
        ),
        migrations.AlterUniqueTogether(
            name='profielnaarorganisatie',
            unique_together={('profiel', 'organisatie')},
        ),
    ]
