# Generated by Django 2.0.2 on 2018-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0052_auto_20180306_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiel',
            name='tussenvoegels',
        ),
        migrations.AddField(
            model_name='profiel',
            name='tussenvoegsel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tussenvoegsel'),
        ),
    ]
