# Generated by Django 2.0.2 on 2018-03-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0053_auto_20180306_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiel',
            old_name='photo',
            new_name='pasfoto',
        ),
    ]
