# Generated by Django 2.0.2 on 2018-03-08 10:48

from django.db import migrations
import jeugdzorg.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jeugdzorg', '0054_auto_20180306_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=jeugdzorg.fields.EmailToLowerField(max_length=254, null=True, unique=True),
        ),
    ]
